### ISSUE TITLE
Vim comment style

### ISSUE THREAD

**Issue by bovine3dom** [ELLIOTTCABLE/excmd-parser#1]
```viml
" this is a comment


// this isn't


"" this is still a comment in VimL
"" but I think we probably are OK to break compatibility
"" and use it for string quoting instead - i.e. these three lines should be errors

/* multiline commments
don't real */

```

https://github.com/ELLIOTTCABLE/excmd-parser/blob/master/src/lexer.ml#L162

It's a bit more complicated than // but still reasonably simple in words - if there's an odd number of " on a line, the last one starts a commment.

:D

Relevant Tridactyl issue: https://github.com/cmcaine/tridactyl/issues/789

**Comment by ELLIOTTCABLE** [comment]
Oh, I just commented in the wrong place — see https://github.com/cmcaine/tridactyl/issues/789#issuecomment-416768088, but basically, I was trying to be “Vim-spirited JavaScript” in terms of lexical conventions: given that JavaScript and “excmd language” are likely to show up in the same file, I wanted the users to have a consistency of lexical conventions; so I was building JavaScript-style comments and string-escapes.

That said, I do not feel particularly strongly about this, and am happy to change it. Lemme know if you find my argument convincing, and if not, I'll swap them out! 🤣

**Comment by bovine3dom** [comment]
I'm going to just talk in the other thread :)
